### ISSUE TITLE
Test site on Internet Explorer

### ISSUE THREAD

**Issue by markpfaff** [markpfaff/WSMA#53]
Please note the page you're on, screen size and any other info like how the bug was triggered etc
Bugs:

**Comment by am-davis** [comment]
(DESKTOP) Will make separate post for Mobile.

ALL PAGES:
There is a "log in" text at the very bottom of the left corner.  I don't know of Firefox does the same thing.  And there is "front-page.php" displayed between about and footer (both Chrome and IE)  Though since the "page.php" is there on all the different browsers I assume it's supposed to be there.

Slow loading, loads in weird patterns before going to the right places.  (specifically the footer)

HOME PAGE
The about blurb on IE9 it's box only goes down till the end of the text.  Same with the latest news and Classes (desktop)

ABOUT PAGE
The calendar in the right is missing the white backgrounds behind the dates. 

INSTRUMENTS BASS PAGE
Enroll buttons have no background, only boarder and text.
Broken link to teachers
